name: auto_doreming_shussha

on: [workflow_dispatch]

# on:
#   schedule:
#     - cron: '0 0 * * 1,2,3,4,5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: grep
        run: |
          pwd
          ls
          #grep `date "+%Y/%-m/%-d",` ./holidays.csv > ./grep_result
          cat ./holidays.csv | sed -n -E -e '/aaa/p' > ./grep_result
          cat ./grep_result
          
      - name: echo csv
        run: |
          echo "${csv}"
